FROM archlinux:latest AS builder

# Install latest release of helix
RUN pacman -Sy rust git helix --noconfirm

# Build helix from latest master
RUN git clone https://github.com/helix-editor/helix.git && \
    cd helix && cargo build --release
RUN rm -rf /helix/runtime/grammars/sources


FROM debian:testing-slim

# Install sandbox tool
RUN apt update && apt install -y bubblewrap

# Add non-root user
RUN useradd -m user

# Add sample helix configuration and runtime
RUN mkdir -p /home/user/.config/helix
COPY config.toml /home/user/.config/helix/config.toml

# Add editor binary
COPY --from=builder /helix/target/release/hx /usr/local/bin/master
COPY --from=builder /usr/bin/helix /usr/local/bin/release
COPY --from=builder /helix/runtime /home/user/.config/helix/runtime

# Add playground rust project
RUN mkdir -p /home/user/playground
COPY playground /home/user/playground

# Allow everyone to access helix and home directory
RUN chmod -R 777 /home/user
RUN chmod -R 777 /usr/local/bin/master
RUN chmod -R 777 /usr/local/bin/release

USER user

# By default run "release --tutor"
ENV HELIX="release"
ENV ARGS="--tutor"

# Run helix inside sandbox
CMD bwrap \
    --bind /usr/local/bin/${HELIX} /usr/local/bin/${HELIX} \
    --bind /usr/bin/sh /usr/bin/sh \
    --ro-bind /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libgcc_s.so.1 \
    --ro-bind /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libm.so.6 \
    --ro-bind /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6 \
    --ro-bind /lib/x86_64-linux-gnu/libstdc++.so.6 /lib/x86_64-linux-gnu/libstdc++.so.6 \
    --ro-bind /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2 \
    --ro-bind /proc/self /proc/self \
    --dir /tmp \
    --tmpfs /home \
    --tmpfs /tmp \
    --die-with-parent \
    --setenv HOME /home/user \
    --setenv TERM xterm \
    --unshare-user \
    --uid 1000 \
    --gid 1000 \
    --bind /home/user/.config/helix /home/user/.config/helix \
    --bind /home/user/playground /home/user/playground \
    /usr/bin/sh -c "cd /home/user/playground && /usr/local/bin/${HELIX} ${ARGS}"
    