name: Build and publish Docker
on:
  # Run this workflow every day
  schedule:
    - cron: "00 00 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: townload/helix-container
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Containerfile
        workdir: helix
  update:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Update docker image
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: podman pull docker.io/townload/helix-container:latest
